## 1) ndarray

In [43]:
import numpy as np
import pandas as pd

In [14]:
a = np.array( [ 1, 2, 3, 4 ] )
a

array([1, 2, 3, 4])

In [18]:
b = np.array( [ 1, 2, 3.1, 4 ] )
b

array([1. , 2. , 3.1, 4. ])

In [20]:
c = np.array( [ 1, '2', 3, 4 ] )
c

array(['1', '2', '3', '4'], dtype='<U21')

In [22]:
print(a)
print(type(a))
print(a.dtype)
print(b)
print(type(b))
print(b.dtype)
print(c)
print(type(c))
print(c.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int64
[1.  2.  3.1 4. ]
<class 'numpy.ndarray'>
float64
['1' '2' '3' '4']
<class 'numpy.ndarray'>
<U21

In [25]:
a =np.array( [ [ 1, 2, 3, 4 ] , [ 5, 6, 7, 8 ] ] )
#a =np.array( [ 1, 2, 3, 4 ] , [ 5, 6, 7, 8 ]  )
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
print(len( a ))
print(len( a[0] ))

2
4

In [33]:
a =np.array( [ [ [ 1 ] ] , [ [ 1 ] ] , [ [ 1 ] ] ] )
#a =np.array( [ [ 1 ], [ 1 ], [ 1 ] ])
a

array([[[1]],

       [[1]],

       [[1]]])

In [36]:
a = np.zeros(10)
b = np.ones(10)
print(a)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

In [37]:
a =np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [40]:
a1 = np.array( [ 1, 2, 3, 4, 5 ])
a2 = np.array( [ [ 1, 2, 3, 4 ] , [ 1, 2, 3, 4 ] ] )
a3 = np.array( [ [ [ 1, 2, 3 ] , [ 1, 2, 3 ] ] ,
                 [ [ 1, 2, 3 ] , [ 1, 2, 3 ] ] ,
                 [ [ 1, 2, 3 ] , [ 1, 2, 3 ] ] ] )
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
print(a1.shape)
print(a2.shape)
print(a3.shape)

1
2
3
(5,)
(2, 4)
(3, 2, 3)

In [41]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

## 2) Series

In [54]:
e = pd.Series([1,2,3,4,5])
e

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [46]:
f = pd.Series([1200, 3500, 2100, 9600],
              index=['사과', '딸기', '키위', '메론'])
f

사과    1200
딸기    3500
키위    2100
메론    9600
dtype: int64

In [49]:
g = pd.Series({'사과': 1200, '딸기': 3500, '키위': 2100, '메론': 9600})
g

사과    1200
딸기    3500
키위    2100
메론    9600
dtype: int64

In [58]:
print(e[0])
print(g['딸기'])

1
3500

In [59]:
f[f == 1200]

사과    1200
dtype: int64

## 3) DataFrame

In [69]:
price = {
    '2020': [2500, 1500, 3000],
    '2021': [2700, 1800, 3600],
    '2022': [3000, 2400, 4200],
    '2023': [3500, 3000, 5600] 
}
#price = [
#    [3500, 3000, 2700, 2500],
#    [3000, 2400, 1800, 1500],
#    [5600, 4200, 3600, 3000]
#]
   
index = [ '사과', '딸기', '키위' ]
columns = ['2023', '2022', '2021', '2020']

In [70]:
df = pd.DataFrame(price, index=index, columns=columns)
df

    2023  2022  2021  2020
사과  3500  3000  2700  2500
딸기  3000  2400  1800  1500
키위  5600  4200  3600  3000

In [71]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, 사과 to 키위
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   2023    3 non-null      int64
 1   2022    3 non-null      int64
 2   2021    3 non-null      int64
 3   2020    3 non-null      int64
dtypes: int64(4)
memory usage: 120.0+ bytes

In [73]:
df.count()

2023    3
2022    3
2021    3
2020    3
dtype: int64

In [75]:
df.shape

(3, 4)

In [76]:
print(len(df)) 
print(len(df.columns))

3
4

In [77]:
df.value_counts()

2023  2022  2021  2020
3500  3000  2700  2500    1
3000  2400  1800  1500    1
5600  4200  3600  3000    1
Name: count, dtype: int64

In [79]:
df['2020'].value_counts()

2020
2500    1
1500    1
3000    1
Name: count, dtype: int64

In [80]:
df = pd.DataFrame( {
    '이름': ['피카츄','라이츄','리자드','리자몽','꼬부기','어니부기'],
    '속성': ['전기', '전기', '불','불','물',None], 
    '색깔': ['노랑', '노랑', None,'빨강','파랑','파랑'],
    '순위': [ 5, 2, 6, 1, 4, 3] })

df.columns = ['이름', '속성','색깔','순위']
df

     이름   속성   색깔  순위
0   피카츄   전기   노랑   5
1   라이츄   전기   노랑   2
2   리자드    불  NaN   6
3   리자몽    불   빨강   1
4   꼬부기    물   파랑   4
5  어니부기  NaN   파랑   3

In [81]:
df['속성']

0     전기
1     전기
2      불
3      불
4      물
5    NaN
Name: 속성, dtype: str

In [82]:
df[['속성']]

    속성
0   전기
1   전기
2    불
3    불
4    물
5  NaN

In [83]:
df[['이름','순위']]

     이름  순위
0   피카츄   5
1   라이츄   2
2   리자드   6
3   리자몽   1
4   꼬부기   4
5  어니부기   3

In [84]:
df['이름'].values

<StringArray>
['피카츄', '라이츄', '리자드', '리자몽', '꼬부기', '어니부기']
Length: 6, dtype: str

In [85]:
df['이름'].shape

(6,)